var annotated =
[
    [ "Eigen", null, [
      [ "internal", null, [
        [ "BandMatrix", "classEigen_1_1internal_1_1BandMatrix.html", "classEigen_1_1internal_1_1BandMatrix" ],
        [ "TridiagonalMatrix", "classEigen_1_1internal_1_1TridiagonalMatrix.html", "classEigen_1_1internal_1_1TridiagonalMatrix" ],
        [ "dense_product_base< Lhs, Rhs, Option, InnerProduct >", "classEigen_1_1internal_1_1dense__product__base_3_01Lhs_00_01Rhs_00_01Option_00_01InnerProduct_01_4.html", "classEigen_1_1internal_1_1dense__product__base_3_01Lhs_00_01Rhs_00_01Option_00_01InnerProduct_01_4" ],
        [ "HessenbergDecompositionMatrixHReturnType", "structEigen_1_1internal_1_1HessenbergDecompositionMatrixHReturnType.html", "structEigen_1_1internal_1_1HessenbergDecompositionMatrixHReturnType" ],
        [ "FullPivHouseholderQRMatrixQReturnType", "structEigen_1_1internal_1_1FullPivHouseholderQRMatrixQReturnType.html", "structEigen_1_1internal_1_1FullPivHouseholderQRMatrixQReturnType" ],
        [ "MappedSuperNodalMatrix", "classEigen_1_1internal_1_1MappedSuperNodalMatrix.html", "classEigen_1_1internal_1_1MappedSuperNodalMatrix" ],
        [ "SparseLUImpl", "classEigen_1_1internal_1_1SparseLUImpl.html", "classEigen_1_1internal_1_1SparseLUImpl" ]
      ] ],
      [ "LDLT", "classEigen_1_1LDLT.html", "classEigen_1_1LDLT" ],
      [ "LLT", "classEigen_1_1LLT.html", "classEigen_1_1LLT" ],
      [ "CholmodBase", "classEigen_1_1CholmodBase.html", "classEigen_1_1CholmodBase" ],
      [ "CholmodSimplicialLLT", "classEigen_1_1CholmodSimplicialLLT.html", "classEigen_1_1CholmodSimplicialLLT" ],
      [ "CholmodSimplicialLDLT", "classEigen_1_1CholmodSimplicialLDLT.html", "classEigen_1_1CholmodSimplicialLDLT" ],
      [ "CholmodSupernodalLLT", "classEigen_1_1CholmodSupernodalLLT.html", "classEigen_1_1CholmodSupernodalLLT" ],
      [ "CholmodDecomposition", "classEigen_1_1CholmodDecomposition.html", "classEigen_1_1CholmodDecomposition" ],
      [ "Array", "classEigen_1_1Array.html", "classEigen_1_1Array" ],
      [ "MatrixWrapper", "classEigen_1_1MatrixWrapper.html", "classEigen_1_1MatrixWrapper" ],
      [ "ArrayBase", "classEigen_1_1ArrayBase.html", "classEigen_1_1ArrayBase" ],
      [ "ArrayWrapper", "classEigen_1_1ArrayWrapper.html", "classEigen_1_1ArrayWrapper" ],
      [ "Block", "classEigen_1_1Block.html", "classEigen_1_1Block" ],
      [ "CommaInitializer", "structEigen_1_1CommaInitializer.html", "structEigen_1_1CommaInitializer" ],
      [ "InnerIterator", "classEigen_1_1InnerIterator.html", "classEigen_1_1InnerIterator" ],
      [ "CwiseBinaryOp", "classEigen_1_1CwiseBinaryOp.html", "classEigen_1_1CwiseBinaryOp" ],
      [ "CwiseNullaryOp", "classEigen_1_1CwiseNullaryOp.html", "classEigen_1_1CwiseNullaryOp" ],
      [ "CwiseTernaryOp", "classEigen_1_1CwiseTernaryOp.html", "classEigen_1_1CwiseTernaryOp" ],
      [ "CwiseUnaryOp", "classEigen_1_1CwiseUnaryOp.html", "classEigen_1_1CwiseUnaryOp" ],
      [ "CwiseUnaryView", "classEigen_1_1CwiseUnaryView.html", "classEigen_1_1CwiseUnaryView" ],
      [ "DenseBase", "classEigen_1_1DenseBase.html", "classEigen_1_1DenseBase" ],
      [ "DenseCoeffsBase< Derived, ReadOnlyAccessors >", "classEigen_1_1DenseCoeffsBase_3_01Derived_00_01ReadOnlyAccessors_01_4.html", "classEigen_1_1DenseCoeffsBase_3_01Derived_00_01ReadOnlyAccessors_01_4" ],
      [ "DenseCoeffsBase< Derived, WriteAccessors >", "classEigen_1_1DenseCoeffsBase_3_01Derived_00_01WriteAccessors_01_4.html", "classEigen_1_1DenseCoeffsBase_3_01Derived_00_01WriteAccessors_01_4" ],
      [ "DenseCoeffsBase< Derived, DirectAccessors >", "classEigen_1_1DenseCoeffsBase_3_01Derived_00_01DirectAccessors_01_4.html", "classEigen_1_1DenseCoeffsBase_3_01Derived_00_01DirectAccessors_01_4" ],
      [ "DenseCoeffsBase< Derived, DirectWriteAccessors >", "classEigen_1_1DenseCoeffsBase_3_01Derived_00_01DirectWriteAccessors_01_4.html", "classEigen_1_1DenseCoeffsBase_3_01Derived_00_01DirectWriteAccessors_01_4" ],
      [ "Diagonal", "classEigen_1_1Diagonal.html", "classEigen_1_1Diagonal" ],
      [ "DiagonalMatrix", "classEigen_1_1DiagonalMatrix.html", "classEigen_1_1DiagonalMatrix" ],
      [ "DiagonalWrapper", "classEigen_1_1DiagonalWrapper.html", "classEigen_1_1DiagonalWrapper" ],
      [ "EigenBase", "structEigen_1_1EigenBase.html", "structEigen_1_1EigenBase" ],
      [ "ForceAlignedAccess", "classEigen_1_1ForceAlignedAccess.html", "classEigen_1_1ForceAlignedAccess" ],
      [ "Inverse", "classEigen_1_1Inverse.html", "classEigen_1_1Inverse" ],
      [ "IOFormat", "structEigen_1_1IOFormat.html", "structEigen_1_1IOFormat" ],
      [ "WithFormat", "classEigen_1_1WithFormat.html", "classEigen_1_1WithFormat" ],
      [ "Map", "classEigen_1_1Map.html", "classEigen_1_1Map" ],
      [ "MapBase< Derived, ReadOnlyAccessors >", "classEigen_1_1MapBase_3_01Derived_00_01ReadOnlyAccessors_01_4.html", "classEigen_1_1MapBase_3_01Derived_00_01ReadOnlyAccessors_01_4" ],
      [ "MapBase< Derived, WriteAccessors >", "classEigen_1_1MapBase_3_01Derived_00_01WriteAccessors_01_4.html", "classEigen_1_1MapBase_3_01Derived_00_01WriteAccessors_01_4" ],
      [ "Matrix", "classEigen_1_1Matrix.html", "classEigen_1_1Matrix" ],
      [ "MatrixBase", "classEigen_1_1MatrixBase.html", "classEigen_1_1MatrixBase" ],
      [ "NestByValue", "classEigen_1_1NestByValue.html", "classEigen_1_1NestByValue" ],
      [ "NoAlias", "classEigen_1_1NoAlias.html", "classEigen_1_1NoAlias" ],
      [ "NumTraits", "structEigen_1_1NumTraits.html", null ],
      [ "PermutationBase", "classEigen_1_1PermutationBase.html", "classEigen_1_1PermutationBase" ],
      [ "PermutationMatrix", "classEigen_1_1PermutationMatrix.html", "classEigen_1_1PermutationMatrix" ],
      [ "PermutationWrapper", "classEigen_1_1PermutationWrapper.html", "classEigen_1_1PermutationWrapper" ],
      [ "Product", "classEigen_1_1Product.html", "classEigen_1_1Product" ],
      [ "Ref", "classEigen_1_1Ref.html", "classEigen_1_1Ref" ],
      [ "Replicate", "classEigen_1_1Replicate.html", "classEigen_1_1Replicate" ],
      [ "Reverse", "classEigen_1_1Reverse.html", "classEigen_1_1Reverse" ],
      [ "Select", "classEigen_1_1Select.html", "classEigen_1_1Select" ],
      [ "SelfAdjointView", "classEigen_1_1SelfAdjointView.html", "classEigen_1_1SelfAdjointView" ],
      [ "Solve", "classEigen_1_1Solve.html", "classEigen_1_1Solve" ],
      [ "SolverBase", "classEigen_1_1SolverBase.html", "classEigen_1_1SolverBase" ],
      [ "Stride", "classEigen_1_1Stride.html", "classEigen_1_1Stride" ],
      [ "InnerStride", "classEigen_1_1InnerStride.html", "classEigen_1_1InnerStride" ],
      [ "OuterStride", "classEigen_1_1OuterStride.html", "classEigen_1_1OuterStride" ],
      [ "Transpose", "classEigen_1_1Transpose.html", "classEigen_1_1Transpose" ],
      [ "Transpositions", "classEigen_1_1Transpositions.html", "classEigen_1_1Transpositions" ],
      [ "TriangularBase", "classEigen_1_1TriangularBase.html", "classEigen_1_1TriangularBase" ],
      [ "TriangularView", "classEigen_1_1TriangularView.html", "classEigen_1_1TriangularView" ],
      [ "TriangularViewImpl< _MatrixType, _Mode, Dense >", "classEigen_1_1TriangularViewImpl_3_01__MatrixType_00_01__Mode_00_01Dense_01_4.html", "classEigen_1_1TriangularViewImpl_3_01__MatrixType_00_01__Mode_00_01Dense_01_4" ],
      [ "Dense", "structEigen_1_1Dense.html", null ],
      [ "Sparse", "structEigen_1_1Sparse.html", null ],
      [ "SolverStorage", "structEigen_1_1SolverStorage.html", null ],
      [ "PermutationStorage", "structEigen_1_1PermutationStorage.html", null ],
      [ "TranspositionsStorage", "structEigen_1_1TranspositionsStorage.html", null ],
      [ "MatrixXpr", "structEigen_1_1MatrixXpr.html", null ],
      [ "ArrayXpr", "structEigen_1_1ArrayXpr.html", null ],
      [ "VectorBlock", "classEigen_1_1VectorBlock.html", "classEigen_1_1VectorBlock" ],
      [ "SparseView", "classEigen_1_1SparseView.html", "classEigen_1_1SparseView" ],
      [ "PartialReduxExpr", "classEigen_1_1PartialReduxExpr.html", "classEigen_1_1PartialReduxExpr" ],
      [ "VectorwiseOp", "classEigen_1_1VectorwiseOp.html", "classEigen_1_1VectorwiseOp" ],
      [ "FullPivLU", "classEigen_1_1FullPivLU.html", "classEigen_1_1FullPivLU" ],
      [ "PartialPivLU", "classEigen_1_1PartialPivLU.html", "classEigen_1_1PartialPivLU" ],
      [ "HouseholderQR", "classEigen_1_1HouseholderQR.html", "classEigen_1_1HouseholderQR" ],
      [ "ColPivHouseholderQR", "classEigen_1_1ColPivHouseholderQR.html", "classEigen_1_1ColPivHouseholderQR" ],
      [ "FullPivHouseholderQR", "classEigen_1_1FullPivHouseholderQR.html", "classEigen_1_1FullPivHouseholderQR" ],
      [ "CompleteOrthogonalDecomposition", "classEigen_1_1CompleteOrthogonalDecomposition.html", "classEigen_1_1CompleteOrthogonalDecomposition" ],
      [ "JacobiSVD", "classEigen_1_1JacobiSVD.html", "classEigen_1_1JacobiSVD" ],
      [ "BDCSVD", "classEigen_1_1BDCSVD.html", "classEigen_1_1BDCSVD" ],
      [ "HouseholderSequence", "classEigen_1_1HouseholderSequence.html", "classEigen_1_1HouseholderSequence" ],
      [ "JacobiRotation", "classEigen_1_1JacobiRotation.html", "classEigen_1_1JacobiRotation" ],
      [ "RotationBase", "classEigen_1_1RotationBase.html", "classEigen_1_1RotationBase" ],
      [ "QuaternionBase", "classEigen_1_1QuaternionBase.html", "classEigen_1_1QuaternionBase" ],
      [ "Rotation2D", "classEigen_1_1Rotation2D.html", "classEigen_1_1Rotation2D" ],
      [ "AngleAxis", "classEigen_1_1AngleAxis.html", "classEigen_1_1AngleAxis" ],
      [ "Translation", "classEigen_1_1Translation.html", "classEigen_1_1Translation" ],
      [ "AlignedBox", "classEigen_1_1AlignedBox.html", "classEigen_1_1AlignedBox" ],
      [ "Quaternion", "classEigen_1_1Quaternion.html", "classEigen_1_1Quaternion" ],
      [ "Transform", "classEigen_1_1Transform.html", "classEigen_1_1Transform" ],
      [ "ParametrizedLine", "classEigen_1_1ParametrizedLine.html", "classEigen_1_1ParametrizedLine" ],
      [ "Hyperplane", "classEigen_1_1Hyperplane.html", "classEigen_1_1Hyperplane" ],
      [ "Homogeneous", "classEigen_1_1Homogeneous.html", "classEigen_1_1Homogeneous" ],
      [ "SparseMatrixBase", "classEigen_1_1SparseMatrixBase.html", "classEigen_1_1SparseMatrixBase" ],
      [ "aligned_allocator", "classEigen_1_1aligned__allocator.html", "classEigen_1_1aligned__allocator" ],
      [ "ScalarBinaryOpTraits", "structEigen_1_1ScalarBinaryOpTraits.html", null ],
      [ "ComplexEigenSolver", "classEigen_1_1ComplexEigenSolver.html", "classEigen_1_1ComplexEigenSolver" ],
      [ "ComplexSchur", "classEigen_1_1ComplexSchur.html", "classEigen_1_1ComplexSchur" ],
      [ "EigenSolver", "classEigen_1_1EigenSolver.html", "classEigen_1_1EigenSolver" ],
      [ "GeneralizedEigenSolver", "classEigen_1_1GeneralizedEigenSolver.html", "classEigen_1_1GeneralizedEigenSolver" ],
      [ "GeneralizedSelfAdjointEigenSolver", "classEigen_1_1GeneralizedSelfAdjointEigenSolver.html", "classEigen_1_1GeneralizedSelfAdjointEigenSolver" ],
      [ "HessenbergDecomposition", "classEigen_1_1HessenbergDecomposition.html", "classEigen_1_1HessenbergDecomposition" ],
      [ "RealQZ", "classEigen_1_1RealQZ.html", "classEigen_1_1RealQZ" ],
      [ "RealSchur", "classEigen_1_1RealSchur.html", "classEigen_1_1RealSchur" ],
      [ "SelfAdjointEigenSolver", "classEigen_1_1SelfAdjointEigenSolver.html", "classEigen_1_1SelfAdjointEigenSolver" ],
      [ "Tridiagonalization", "classEigen_1_1Tridiagonalization.html", "classEigen_1_1Tridiagonalization" ],
      [ "Map< const Quaternion< _Scalar >, _Options >", "classEigen_1_1Map_3_01const_01Quaternion_3_01__Scalar_01_4_00_01__Options_01_4.html", "classEigen_1_1Map_3_01const_01Quaternion_3_01__Scalar_01_4_00_01__Options_01_4" ],
      [ "Map< Quaternion< _Scalar >, _Options >", "classEigen_1_1Map_3_01Quaternion_3_01__Scalar_01_4_00_01__Options_01_4.html", "classEigen_1_1Map_3_01Quaternion_3_01__Scalar_01_4_00_01__Options_01_4" ],
      [ "DiagonalPreconditioner", "classEigen_1_1DiagonalPreconditioner.html", "classEigen_1_1DiagonalPreconditioner" ],
      [ "LeastSquareDiagonalPreconditioner", "classEigen_1_1LeastSquareDiagonalPreconditioner.html", "classEigen_1_1LeastSquareDiagonalPreconditioner" ],
      [ "IdentityPreconditioner", "classEigen_1_1IdentityPreconditioner.html", "classEigen_1_1IdentityPreconditioner" ],
      [ "BiCGSTAB", "classEigen_1_1BiCGSTAB.html", "classEigen_1_1BiCGSTAB" ],
      [ "ConjugateGradient", "classEigen_1_1ConjugateGradient.html", "classEigen_1_1ConjugateGradient" ],
      [ "IncompleteCholesky", "classEigen_1_1IncompleteCholesky.html", "classEigen_1_1IncompleteCholesky" ],
      [ "IncompleteLUT", "classEigen_1_1IncompleteLUT.html", "classEigen_1_1IncompleteLUT" ],
      [ "IterativeSolverBase", "classEigen_1_1IterativeSolverBase.html", "classEigen_1_1IterativeSolverBase" ],
      [ "LeastSquaresConjugateGradient", "classEigen_1_1LeastSquaresConjugateGradient.html", "classEigen_1_1LeastSquaresConjugateGradient" ],
      [ "SolveWithGuess", "classEigen_1_1SolveWithGuess.html", "classEigen_1_1SolveWithGuess" ],
      [ "MetisOrdering", "classEigen_1_1MetisOrdering.html", "classEigen_1_1MetisOrdering" ],
      [ "AMDOrdering", "classEigen_1_1AMDOrdering.html", "classEigen_1_1AMDOrdering" ],
      [ "NaturalOrdering", "classEigen_1_1NaturalOrdering.html", "classEigen_1_1NaturalOrdering" ],
      [ "COLAMDOrdering", "classEigen_1_1COLAMDOrdering.html", "classEigen_1_1COLAMDOrdering" ],
      [ "PardisoLU", "classEigen_1_1PardisoLU.html", "classEigen_1_1PardisoLU" ],
      [ "PardisoLLT", "classEigen_1_1PardisoLLT.html", "classEigen_1_1PardisoLLT" ],
      [ "PardisoLDLT", "classEigen_1_1PardisoLDLT.html", "classEigen_1_1PardisoLDLT" ],
      [ "PastixLU", "classEigen_1_1PastixLU.html", "classEigen_1_1PastixLU" ],
      [ "PastixLLT", "classEigen_1_1PastixLLT.html", "classEigen_1_1PastixLLT" ],
      [ "PastixLDLT", "classEigen_1_1PastixLDLT.html", "classEigen_1_1PastixLDLT" ],
      [ "SimplicialCholeskyBase", "classEigen_1_1SimplicialCholeskyBase.html", "classEigen_1_1SimplicialCholeskyBase" ],
      [ "SimplicialLLT", "classEigen_1_1SimplicialLLT.html", "classEigen_1_1SimplicialLLT" ],
      [ "SimplicialLDLT", "classEigen_1_1SimplicialLDLT.html", "classEigen_1_1SimplicialLDLT" ],
      [ "SimplicialCholesky", "classEigen_1_1SimplicialCholesky.html", "classEigen_1_1SimplicialCholesky" ],
      [ "MappedSparseMatrix", "classEigen_1_1MappedSparseMatrix.html", "classEigen_1_1MappedSparseMatrix" ],
      [ "BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >", "classEigen_1_1BlockImpl_3_01XprType_00_01BlockRows_00_01BlockCols_00_01InnerPanel_00_01Sparse_01_4.html", "classEigen_1_1BlockImpl_3_01XprType_00_01BlockRows_00_01BlockCols_00_01InnerPanel_00_01Sparse_01_4" ],
      [ "SparseCompressedBase", "classEigen_1_1SparseCompressedBase.html", "classEigen_1_1SparseCompressedBase" ],
      [ "SparseMapBase< Derived, ReadOnlyAccessors >", "classEigen_1_1SparseMapBase_3_01Derived_00_01ReadOnlyAccessors_01_4.html", "classEigen_1_1SparseMapBase_3_01Derived_00_01ReadOnlyAccessors_01_4" ],
      [ "SparseMapBase< Derived, WriteAccessors >", "classEigen_1_1SparseMapBase_3_01Derived_00_01WriteAccessors_01_4.html", "classEigen_1_1SparseMapBase_3_01Derived_00_01WriteAccessors_01_4" ],
      [ "Map< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >", "classEigen_1_1Map_3_01SparseMatrix_3_01MatScalar_00_01MatOptions_00_01MatIndex_01_4_00_01Options_00_01StrideType_01_4.html", "classEigen_1_1Map_3_01SparseMatrix_3_01MatScalar_00_01MatOptions_00_01MatIndex_01_4_00_01Options_00_01StrideType_01_4" ],
      [ "SparseMatrix", "classEigen_1_1SparseMatrix.html", "classEigen_1_1SparseMatrix" ],
      [ "Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >", "classEigen_1_1Ref_3_01SparseMatrix_3_01MatScalar_00_01MatOptions_00_01MatIndex_01_4_00_01Options_00_01StrideType_01_4.html", "classEigen_1_1Ref_3_01SparseMatrix_3_01MatScalar_00_01MatOptions_00_01MatIndex_01_4_00_01Options_00_01StrideType_01_4" ],
      [ "Ref< SparseVector< MatScalar, MatOptions, MatIndex >, Options, StrideType >", "classEigen_1_1Ref_3_01SparseVector_3_01MatScalar_00_01MatOptions_00_01MatIndex_01_4_00_01Options_00_01StrideType_01_4.html", "classEigen_1_1Ref_3_01SparseVector_3_01MatScalar_00_01MatOptions_00_01MatIndex_01_4_00_01Options_00_01StrideType_01_4" ],
      [ "SparseSelfAdjointView", "classEigen_1_1SparseSelfAdjointView.html", "classEigen_1_1SparseSelfAdjointView" ],
      [ "SparseSolverBase", "classEigen_1_1SparseSolverBase.html", "classEigen_1_1SparseSolverBase" ],
      [ "TriangularViewImpl< MatrixType, Mode, Sparse >", "classEigen_1_1TriangularViewImpl_3_01MatrixType_00_01Mode_00_01Sparse_01_4.html", "classEigen_1_1TriangularViewImpl_3_01MatrixType_00_01Mode_00_01Sparse_01_4" ],
      [ "SparseVector", "classEigen_1_1SparseVector.html", "classEigen_1_1SparseVector" ],
      [ "Triplet", "classEigen_1_1Triplet.html", "classEigen_1_1Triplet" ],
      [ "SparseLU", "classEigen_1_1SparseLU.html", "classEigen_1_1SparseLU" ],
      [ "SparseQR", "classEigen_1_1SparseQR.html", "classEigen_1_1SparseQR" ],
      [ "SPQR", "classEigen_1_1SPQR.html", "classEigen_1_1SPQR" ],
      [ "SuperLUBase", "classEigen_1_1SuperLUBase.html", "classEigen_1_1SuperLUBase" ],
      [ "SuperLU", "classEigen_1_1SuperLU.html", "classEigen_1_1SuperLU" ],
      [ "SVDBase", "classEigen_1_1SVDBase.html", "classEigen_1_1SVDBase" ],
      [ "UmfPackLU", "classEigen_1_1UmfPackLU.html", "classEigen_1_1UmfPackLU" ]
    ] ],
    [ "internal", null, [
      [ "basic_buffer", "classinternal_1_1basic__buffer.html", "classinternal_1_1basic__buffer" ],
      [ "is_like_std_string", "classinternal_1_1is__like__std__string.html", null ],
      [ "is_tuple_like_", "classinternal_1_1is__tuple__like__.html", null ]
    ] ],
    [ "pteros", null, [
      [ "Data_container", "structpteros_1_1Data__container.html", "structpteros_1_1Data__container" ],
      [ "Babel_wrapper", "classpteros_1_1Babel__wrapper.html", "classpteros_1_1Babel__wrapper" ],
      [ "DCD_file", "classpteros_1_1DCD__file.html", "classpteros_1_1DCD__file" ],
      [ "GRO_file", "classpteros_1_1GRO__file.html", "classpteros_1_1GRO__file" ],
      [ "Gromacs_trajectory_file", "classpteros_1_1Gromacs__trajectory__file.html", "classpteros_1_1Gromacs__trajectory__file" ],
      [ "MOL2_file", "classpteros_1_1MOL2__file.html", "classpteros_1_1MOL2__file" ],
      [ "PDB_file", "classpteros_1_1PDB__file.html", "classpteros_1_1PDB__file" ],
      [ "TNG_file", "classpteros_1_1TNG__file.html", "classpteros_1_1TNG__file" ],
      [ "TRR_file", "classpteros_1_1TRR__file.html", "classpteros_1_1TRR__file" ],
      [ "VMD_molfile_plugin_wrapper", "classpteros_1_1VMD__molfile__plugin__wrapper.html", "classpteros_1_1VMD__molfile__plugin__wrapper" ],
      [ "XTC_file", "classpteros_1_1XTC__file.html", "classpteros_1_1XTC__file" ],
      [ "XYZ_file", "classpteros_1_1XYZ__file.html", "classpteros_1_1XYZ__file" ],
      [ "Selection_parser", "classpteros_1_1Selection__parser.html", "classpteros_1_1Selection__parser" ],
      [ "Frame_info", "structpteros_1_1Frame__info.html", "structpteros_1_1Frame__info" ],
      [ "Options", "classpteros_1_1Options.html", "classpteros_1_1Options" ],
      [ "Task_plugin", "classpteros_1_1Task__plugin.html", "classpteros_1_1Task__plugin" ],
      [ "Trajectory_reader", "classpteros_1_1Trajectory__reader.html", "classpteros_1_1Trajectory__reader" ],
      [ "Atom", "classpteros_1_1Atom.html", "classpteros_1_1Atom" ],
      [ "Atom_proxy", "classpteros_1_1Atom__proxy.html", "classpteros_1_1Atom__proxy" ],
      [ "Distance_search_within", "classpteros_1_1Distance__search__within.html", "classpteros_1_1Distance__search__within" ],
      [ "Force_field", "classpteros_1_1Force__field.html", "classpteros_1_1Force__field" ],
      [ "Grid", "classpteros_1_1Grid.html", "classpteros_1_1Grid" ],
      [ "Mol_file", "classpteros_1_1Mol__file.html", "classpteros_1_1Mol__file" ],
      [ "Periodic_box", "classpteros_1_1Periodic__box.html", "classpteros_1_1Periodic__box" ],
      [ "Pteros_error", "classpteros_1_1Pteros__error.html", "classpteros_1_1Pteros__error" ],
      [ "Selection", "classpteros_1_1Selection.html", "classpteros_1_1Selection" ],
      [ "Frame", "structpteros_1_1Frame.html", "structpteros_1_1Frame" ],
      [ "System", "classpteros_1_1System.html", "classpteros_1_1System" ],
      [ "Histogram", "classpteros_1_1Histogram.html", "classpteros_1_1Histogram" ],
      [ "Histogram2D", "classpteros_1_1Histogram2D.html", "classpteros_1_1Histogram2D" ],
      [ "GNM", "classpteros_1_1GNM.html", "classpteros_1_1GNM" ]
    ] ],
    [ "spdlog", null, [
      [ "sinks", null, [
        [ "ansicolor_sink", "classspdlog_1_1sinks_1_1ansicolor__sink.html", "classspdlog_1_1sinks_1_1ansicolor__sink" ],
        [ "syslog_sink", "classspdlog_1_1sinks_1_1syslog__sink.html", "classspdlog_1_1sinks_1_1syslog__sink" ]
      ] ]
    ] ],
    [ "arg_formatter", "classarg__formatter.html", "classarg__formatter" ],
    [ "basic_cstring_view", "classbasic__cstring__view.html", "classbasic__cstring__view" ],
    [ "basic_fixed_buffer", "classbasic__fixed__buffer.html", "classbasic__fixed__buffer" ],
    [ "basic_format_args", "classbasic__format__args.html", "classbasic__format__args" ],
    [ "basic_memory_buffer", "classbasic__memory__buffer.html", "classbasic__memory__buffer" ],
    [ "basic_printf_context", "classbasic__printf__context.html", "classbasic__printf__context" ],
    [ "basic_string_view", "classbasic__string__view.html", "classbasic__string__view" ],
    [ "basic_writer", "classbasic__writer.html", "classbasic__writer" ],
    [ "format_arg_store", "classformat__arg__store.html", "classformat__arg__store" ],
    [ "format_args", "structformat__args.html", "structformat__args" ],
    [ "format_error", "classformat__error.html", "classformat__error" ],
    [ "format_int", "classformat__int.html", "classformat__int" ],
    [ "printf_arg_formatter", "classprintf__arg__formatter.html", "classprintf__arg__formatter" ],
    [ "Scaling", "classScaling.html", null ],
    [ "system_error", "classsystem__error.html", "classsystem__error" ]
];